### ISSUE TITLE
Unexpected Application Error!

### ISSUE THREAD

**Issue by Jason9612** [mteamwhy/mt-web-pre#146]
Unexpected Application Error!
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
Error: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at pl (https://kp.m-team.cc/static/js/main.8e9cfc06.js:2:1467182)
    at hl (https://kp.m-team.cc/static/js/main.8e9cfc06.js:2:1468441)
    at gl (https://kp.m-team.cc/static/js/main.8e9cfc06.js:2:1468901)
    at hl (https://kp.m-team.cc/static/js/main.8e9cfc06.js:2:1468591)
    at gl (https://kp.m-team.cc/static/js/main.8e9cfc06.js:2:1468839)
    at hl (https://kp.m-team.cc/static/js/main.8e9cfc06.js:2:1468591)
    at gl (https://kp.m-team.cc/static/js/main.8e9cfc06.js:2:1468704)
    at hl (https://kp.m-team.cc/static/js/main.8e9cfc06.js:2:1468591)
    at gl (https://kp.m-team.cc/static/js/main.8e9cfc06.js:2:1470019)
    at hl (https://kp.m-team.cc/static/js/main.8e9cfc06.js:2:1468591)

**Comment by Jason9612** [comment]
发现是chrome翻译 的问题，关掉就好了
